name: Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: ['windows-2019', 'macos-10.15', ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Build the launcher
      run: cargo build --verbose
